### PR TITLE
made some changes

### PR DESCRIPTION
**Pull request by Jay-Dodhiawala**
update format

### CODE REVIEW

**Review by Trkun — COMMENTED** [review]
I don't quite get the use of "wallet name", as it seems to suggest users can have multiple wallets. Or it's just a function that enables customization of your wallet?

**Comment by Jay-Dodhiawala** [comment]
Yeah, I thought user can create multiple wallets but if that is not the case we can remove that parameter

**Comment by Trkun** [comment]
Well let's wait for review from Arsh and see what he thinks.

**Review by Trkun — APPROVED** [review]

**Comment by ArshSB** [comment]
Looks good to me

**Pull request merged**
